### ISSUE TITLE
.map emptied after compile

### ISSUE THREAD

**Issue by VuRkka** [glhrmfrts/q1compile#6]
i compiled a .map and it all went as expected but when i opened the source later it was empty(0kb). got no logs and no settings were saved.
win 10 2004

**Comment by glhrmfrts** [comment]
ok I was able to reproduce this by setting the "Work Dir" to the same directory where the .map file is, do you remember if this was your case @VuRkka ?

**Comment by VuRkka** [comment]
cant quite remember, guess so. what's the purpose of the work dir then?

**Comment by glhrmfrts** [comment]
It's meant to be a place where the compiler can spit temporary/log files in order to not pollute the source or the output directory, hence why it comes pointing to the system's temp dir as the default.

I was used to the necros' compiling gui workflow so I replicated that here. However, I don't know anymore if users care about setting this directory, so I'm thinking of removing this setting. What do you think?

**Comment by glhrmfrts** [comment]
Fixed in v0.6, feel free to re-open if a similar issue arises.
